name: "Security-Gates"
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branches
        run: |
          echo ${{ github.event.repository.default_branch }}
          ls -la
          
  security-gates:
    uses: test-ty-devsecops/action-monorepo/.github/workflows/security-gates.yml@main
    needs: my_first_job
    permissions:
      actions: read
      contents: read
      security-events: write
